on:
  push:
    branches-ignore:
      - main
    tags-ignore:

jobs:
  remote-workflow:
    uses: asanchezo-duoc/AUY1104-SharedWorkflows/.github/workflows/test-code.yaml@main
    with:
      image-name: ${{ vars.DOCKER_IMAGE_NAME }}
      image-tag: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
